# -*- coding: utf-8 -*-
"""PANDAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12rwG-s3WpqUvojRBDOSa-6xw7zTIoiwK
"""

import pandas as pd

data = {
    'Producto': ['Laptop', 'Mouse', 'Teclado', 'Monitor', 'Mouse', 'Laptop'],
    'Categoria': ['Tecnología', 'Accesorios', 'Accesorios', 'Tecnología', 'Accesorios', 'Tecnología'],
    'Precio': [1200.0, 25.0, 45.0, 300.0, None, 1200.0],
    'Cantidad': [2, 10, 5, 3, 15, 1]
}

df = pd.DataFrame(data)

df['Precio'] = df['Precio'].fillna(df['Precio'].mean())
df = df.drop_duplicates()

df['Ingreso_Total'] = df['Precio'] * df['Cantidad']

ventas_por_categoria = df.groupby('Categoria')['Ingreso_Total'].sum().reset_index()

print("--- DataFrame Limpio y Procesado ---")
print(df)
print("\n--- Ventas Totales por Categoría ---")
print(ventas_por_categoria)

import pandas as pd


transacciones = pd.DataFrame({
    'ID_Transaccion': [101, 102, 103, 104],
    'ID_Cliente': [1, 2, 1, 3],
    'Fecha': pd.to_datetime(['2026-06-01', '2026-06-02', '2026-06-03', '2026-06-03']),
    'Monto': [150.50, 80.0, 200.0, 45.0]
})

clientes = pd.DataFrame({
    'ID_Cliente': [1, 2, 3],
    'Ciudad': ['Quito', 'Guayaquil', 'Cuenca']
})

df_unificado = pd.merge(transacciones, clientes, on='ID_Cliente', how='inner')

ventas_por_dia = df_unificado.groupby('Fecha')['Monto'].sum()

print("--- DataFrame Unificado (Transacciones + Clientes) ---")
print(df_unificado)
print("\n--- Monto Total de Ventas por Día ---")
print(ventas_por_dia)